apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage
  labels: 
    apps: webpage1
spec:
  selector:
    matchLabels:
      apps: webpage1

  replicas: 2
  template:
    metadata:
      labels: 
        apps: webpage1
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']      
      containers:
        - name: usermgmt-webapp
          image: stacksimplify/kube-usermgmt-webapp:1.0.0-MySQLDB
          imagePullPolicy: Always
          ports: 
            - containerPort: 8080           
          env:
            - name: DB_HOSTNAME
              value: "mysql-service.default.svc.cluster.local"          
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "webappdb"
            - name: DB_USERNAME
              value: "root"            
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: mysql-root-password
